spring.application.name=excepciones_manejo
spring.datasource.url=jdbc:postgresql://db:5432/db_spring
spring.datasource.username=usuario
spring.datasource.password=usuario
spring.jpa.hibernate.ddl-auto=update
